// scripts/torre-nova-radar-processos.pw.ts — E2E (Playwright) do RADAR e de PROCESSOS (por fase), contra o PALCO.
//
//   node --import tsx scripts/torre-nova-radar-processos.pw.ts            (palco vivo: ver prototipo-torre/COMO-RODAR.md)
//
// NÃO entra na suíte crítica (precisa de servidor). Lê porta e token de /private/tmp/claude-501/torre-nova-dev.json. Só LÊ e exporta
// (não escreve no banco do palco). Cada verificação é um item do CHECKLIST-T (T128–T227) exercido na tela real em 1440×900.
import { chromium, type Page } from "playwright"
import { readFileSync, mkdirSync } from "node:fs"

const d = JSON.parse(readFileSync("/private/tmp/claude-501/torre-nova-dev.json", "utf8"))
const BASE = `http://localhost:${d.porta}`
let passou = 0, falhou = 0
const ok = (n: string, c: boolean, extra = "") => { if (c) { passou++; console.log(`  ✅ ${n}${extra ? ` — ${extra}` : ""}`) } else { falhou++; console.log(`  ❌ ${n}${extra ? ` — ${extra}` : ""}`) } }
const secao = (t: string) => console.log(`\n${t}`)

async function abrir(page: Page, aba: string) {
  await page.goto(`${BASE}/torre?aba=${aba}`, { waitUntil: "networkidle", timeout: 180000 })
  await page.waitForTimeout(2500)
}
const linhasDoRadar = (page: Page) => page.locator(".tor-radar-linha:not(.cab)")
const linhasDeProcessos = (page: Page) => page.locator(".tor-pf-linha")
const numeroDo = (txt: string | null) => Number((txt ?? "").replace(/\D+/g, ""))

async function main() {
  mkdirSync("prototipo-torre/impl", { recursive: true })
  const browser = await chromium.launch()
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 1500 }, acceptDownloads: true })
  await ctx.addCookies([{ name: "authToken", value: d.tokenAdmin, url: BASE }])
  await ctx.addInitScript(([t, u]) => { localStorage.setItem("authToken", t); localStorage.setItem("token", t); localStorage.setItem("user", JSON.stringify(u)) }, [d.tokenAdmin, d.usuarioAdmin])
  const page = await ctx.newPage()
  const erros: string[] = []
  page.on("pageerror", (e) => erros.push("pageerror: " + e.message))
  page.on("response", (r) => { if (r.status() >= 400 && r.url().includes("/api/")) erros.push(`${r.status()} ${r.url()}`) })

  secao("RADAR")
  await abrir(page, "radar")
  ok("T128 trilha 'Torre de Controle › Radar' e título", (await page.locator(".tor-pg-trilha").innerText()).includes("Torre de Controle › Radar") && (await page.locator(".tor-pg-titulo").innerText()) === "Radar · cada família em cada fase")
  const chips = page.locator("[aria-label='Filtro do Radar'] button")
  ok("T130 cinco botões: Todas · Precisam de alguém · Bola nossa · Bola com terceiro · Críticas, com contagem", (await chips.count()) === 5 && /^Todas \d+$/.test((await chips.nth(0).innerText()).trim()) && /^Críticas \d+$/.test((await chips.nth(4).innerText()).trim()))
  ok("T131 o filtro padrão é 'Precisam de alguém'", (await chips.nth(1).getAttribute("aria-pressed")) === "true")
  const nTodas = numeroDo(await chips.nth(0).innerText()), nPrecisam = numeroDo(await chips.nth(1).innerText())
  ok("T164 rodapé 'Mostrando N de <nº do botão> famílias · ordem: mais grave primeiro'", (await page.locator(".tor-radar-rodape span").first().innerText()).includes(`de ${nPrecisam} `) && (await page.locator(".tor-radar-rodape span").first().innerText()).includes("ordem: mais grave primeiro"))
  const n0 = await linhasDoRadar(page).count()
  ok("T133 cada linha do filtro padrão tem uma célula atual ≠ 'no ritmo'", n0 > 0 && (await page.locator(".tor-rc.atual.ok").count()) === 0)
  await page.screenshot({ path: "prototipo-torre/impl/radar-e2e-padrao.png" })
  await chips.nth(0).click()
  ok("T132 'Todas' mostra todas as famílias (paginado)", (await linhasDoRadar(page).count()) === Math.min(12, nTodas))
  if (nTodas > 12) {
    ok("T167 paginação REAL: botões de página clicáveis (1 · 2 …)", (await page.locator("[aria-label='Páginas do Radar'] button").count()) >= 2)
    await page.locator("[aria-label='Páginas do Radar'] button", { hasText: "2" }).first().click()
    ok("…a página 2 mostra o resto e o rodapé acompanha", (await linhasDoRadar(page).count()) === Math.min(12, nTodas - 12) && (await page.locator(".tor-radar-rodape span").first().innerText()).startsWith(`Mostrando ${Math.min(12, nTodas - 12)} de ${nTodas}`))
  }
  await chips.nth(4).click()
  const nCrit = numeroDo(await chips.nth(4).innerText())
  ok("T136 'Críticas': só células vermelhas, uma linha por processo crítico", (await linhasDoRadar(page).count()) === Math.min(12, nCrit) && (await page.locator(".tor-rc.atual:not(.critico)").count()) === 0)
  await chips.nth(2).click()
  ok("T134 'Bola nossa': todas as células atuais dizem 'Nossa'", (await page.locator(".tor-rc.atual span").allInnerTexts()).every((t) => t.startsWith("Nossa")))
  await chips.nth(3).click()
  ok("T135 'Bola com terceiro': nenhuma célula atual diz 'Nossa'", (await page.locator(".tor-rc.atual span").allInnerTexts()).every((t) => !t.startsWith("Nossa")))
  await chips.nth(0).click()
  await page.getByLabel("Buscar família", { exact: true }).fill("BELLANDI")
  ok("T137 busca por família (sem acento/maiúsculas)", (await linhasDoRadar(page).count()) === 1 && (await linhasDoRadar(page).first().innerText()).includes("Bellandi"))
  ok("…os botões não mexem com a busca; o rodapé diz o recorte", numeroDo(await chips.nth(0).innerText()) === nTodas && (await page.locator(".tor-radar-rodape span").first().innerText()).startsWith("Mostrando 1 de 1 família"))
  await page.getByLabel("Buscar família", { exact: true }).fill("zzzzzz")
  ok("T166 sem resultado: 'Nenhuma família encontrada com esses filtros.' (uma vez só)", (await page.getByText("Nenhuma família encontrada com esses filtros.").count()) === 1 && (await linhasDoRadar(page).count()) === 0)
  await page.getByLabel("Buscar família", { exact: true }).fill("")
  const paises = await page.getByLabel("País", { exact: true }).locator("option").allInnerTexts()
  ok("T138 select País: 'Todos os países' + os países presentes", paises[0] === "Todos os países" && paises.length >= 2, paises.join(" | "))
  await page.getByLabel("País", { exact: true }).selectOption({ label: paises[1] })
  ok("…filtra por país (todas as linhas do país escolhido)", (await linhasDoRadar(page).allInnerTexts()).every((t) => t.includes(paises[1])))
  await page.getByLabel("País", { exact: true }).selectOption({ label: "Todos os países" })
  const ordens = await page.getByLabel("Ordenar", { exact: true }).locator("option").allInnerTexts()
  ok("T139 select Ordenar: Mais grave primeiro · Mais tempo na fase · Família A–Z", ordens.join(" | ") === "Mais grave primeiro | Mais tempo na fase | Família A–Z")
  await page.getByLabel("Ordenar", { exact: true }).selectOption({ label: "Família A–Z" })
  const nomes = (await page.locator(".tor-radar-fam b").allInnerTexts())
  ok("T142 Família A–Z (pt-BR)", nomes.length > 1 && JSON.stringify(nomes) === JSON.stringify([...nomes].sort((a, b) => a.localeCompare(b, "pt-BR"))))
  ok("T143 texto explicativo + T144 cabeçalho com (cond.)", (await page.getByText("Clique na família para abrir o processo.").count()) === 1 && (await page.locator(".tor-radar-linha.cab").innerText()).includes("(cond.)"))
  ok("T146/T148/T149 células: ✓ (feita), — (futura) e a atual com 2 linhas (bola · tempo / risco)", (await page.locator(".tor-rc.feita").count()) > 0 && (await page.locator(".tor-rc.futura").count()) > 0 && (await page.locator(".tor-rc.atual small").count()) > 0)
  ok("T168 legenda completa", (await page.locator(".tor-radar-legenda span").count()) === 5)
  const primeiraFamilia = page.locator(".tor-radar-fam").first()
  const href = await primeiraFamilia.getAttribute("href")
  await primeiraFamilia.click()
  await page.waitForURL(/\/torre\/processo\/\d+/, { timeout: 60000 })
  ok("T169 clicar na família abre o Processo (/torre/processo/[id])", /\/torre\/processo\/\d+$/.test(page.url()) && page.url().endsWith(href ?? "x"), page.url())

  secao("PROCESSOS (por fase)")
  await abrir(page, "processos")
  const titulo = await page.locator(".tor-pg-titulo").innerText()
  ok("T170/T171 trilha e título '<fase> · N processos'", /^.+ · \d+ process/.test(titulo) && (await page.locator(".tor-pg-trilha").innerText()).startsWith("Torre de Controle › Processos ›"), titulo)
  ok("T172 busca de 300 px com o placeholder do protótipo", (await page.getByPlaceholder("Buscar família, pessoa, cartório…").count()) === 1)
  ok("T174 'Escolha a fase — a tabela abaixo mostra só os processos dela'", (await page.getByText("Escolha a fase — a tabela abaixo mostra só os processos dela").count()) === 1)
  const botoes = page.locator("[aria-label='Fase'] button")
  const nFases = await botoes.count()
  ok("T175 um botão por fase, com contagem", nFases >= 9 && (await botoes.allInnerTexts()).every((t) => /\d+$/.test(t.trim())), `${nFases} fases`)
  ok("T176 fase padrão = a de maior volume", (await page.locator("[aria-label='Fase'] button[aria-pressed='true']").count()) === 1)
  ok("T178 cartão 'Saúde da fase' (no ritmo · atenção · parados · tempo médio real · meta)", (await page.locator("[aria-label='Saúde da fase']").innerText()).includes("tempo médio real · meta") && (await page.locator(".tor-pf-barra").count()) === 1)
  ok("T188 cartão 'Onde estão as N certidões desta fase — por passo' com caixas e frase de gargalo", /Onde estão as [\d.]+ (certidões|tarefas) desta fase — por passo/i.test(await page.locator("[aria-label^='Onde estão']").innerText()) && (await page.locator(".tor-pf-caixa").count()) >= 3)
  const filtros = page.locator("[aria-label='Situação'] button")
  ok("T194 quatro filtros: Todos · Precisam de alguém · Atenção · Parados ou sem dono", (await filtros.count()) === 4 && (await filtros.nth(3).innerText()).startsWith("Parados ou sem dono"))
  const nTodos = numeroDo(await filtros.nth(0).innerText()), nAt = numeroDo(await filtros.nth(2).innerText()), nPa = numeroDo(await filtros.nth(3).innerText()), nPrec = numeroDo(await filtros.nth(1).innerText())
  ok("T194/T195 'Precisam' = atenção + parados ou sem dono", nPrec === nAt + nPa)
  ok("T200 colunas da tabela, na ordem do protótipo", (await page.locator(".tor-pf-cab").innerText()).replace(/\s+/g, " ").toUpperCase().includes("FAMÍLIA · PAÍS NA FASE HÁ CERTIDÕES PRONTAS PASSO ONDE A MAIORIA ESTÁ BOLA COM PRÓXIMA AÇÃO RESPONSÁVEL PRAZO SITUAÇÃO AÇÕES"))
  const nLinhas = await linhasDeProcessos(page).count()
  ok("T222 rodapé 'Mostrando N de <nº do filtro> processos da fase · 12 por página'", nLinhas === Math.min(12, nTodos) && (await page.locator(".tor-pf-rodape span").first().innerText()) === `Mostrando ${nLinhas} de ${nTodos} ${nTodos === 1 ? "processo" : "processos"} da fase · 12 por página`)
  ok("T203 'Certidões prontas' carrega 'a de b' pela fonte única (não fica em '…')", await page.waitForFunction(() => ![...document.querySelectorAll(".tor-pf-prontas b")].some((b) => b.textContent === "…"), null, { timeout: 60000 }).then(() => true).catch(() => false))
  ok("T201 família + 'País · N requerentes'", /\w+ · \d+ requerentes?/.test(await page.locator(".tor-pf-fam span").first().innerText()))
  ok("T204 'Bola com' em pílula (Nossa âmbar / outras cinza)", (await page.locator(".tor-pf-pilula.nossa, .tor-pf-pilula.outra").count()) >= nLinhas)
  ok("T207 situação em pílula (No ritmo/Atenção/Parado/Sem dono)", (await page.locator(".tor-pf-linha .tor-pf-pilula.ok, .tor-pf-linha .tor-pf-pilula.at, .tor-pf-linha .tor-pf-pilula.pa, .tor-pf-linha .tor-pf-pilula.sd").count()) === nLinhas)
  await page.screenshot({ path: "prototipo-torre/impl/processos-e2e-padrao.png" })
  await filtros.nth(3).click()
  const situacoes = await page.locator(".tor-pf-linha .tor-pf-pilula.pa, .tor-pf-linha .tor-pf-pilula.sd").count()
  ok("T195 'Parados ou sem dono': só Parado/Sem dono", situacoes === (await linhasDeProcessos(page).count()) && situacoes === Math.min(12, nPa))
  await filtros.nth(0).click()
  const resps = await page.getByLabel("Responsável", { exact: true }).locator("option").allInnerTexts()
  ok("T197 select Responsável: 'Todos os responsáveis' + nomes", resps[0] === "Todos os responsáveis" && resps.length >= 2, resps.join(" | "))
  const nomeResp = resps.find((r) => r !== "Todos os responsáveis" && r !== "Sem responsável")
  if (nomeResp) {
    await page.getByLabel("Responsável", { exact: true }).selectOption({ label: nomeResp })
    const respCelulas = await page.locator(".tor-pf-linha").evaluateAll((els) => els.map((e) => e.children[6]?.textContent ?? ""))
    ok("…filtra pelo responsável da linha (igualdade)", respCelulas.length > 0 && respCelulas.every((t) => t === nomeResp))
    await page.getByLabel("Responsável", { exact: true }).selectOption({ label: "Todos os responsáveis" })
  }
  const ordensP = await page.getByLabel("Ordenar", { exact: true }).locator("option").allInnerTexts()
  ok("T198 select Ordenar com as 4 opções", ordensP.join(" | ") === "Ordenar: mais atrasado primeiro | Prazo mais próximo | Entrou na fase há mais tempo | Família A–Z")
  await page.getByLabel("Ordenar", { exact: true }).selectOption({ label: "Família A–Z" })
  const nomesP = await page.locator(".tor-pf-fam a").allInnerTexts()
  ok("…Família A–Z (pt-BR)", JSON.stringify(nomesP) === JSON.stringify([...nomesP].sort((a, b) => a.localeCompare(b, "pt-BR"))))
  await page.getByPlaceholder("Buscar família, pessoa, cartório…").fill("zzzzzz")
  ok("T224 sem resultado: rodapé 'Nenhum processo encontrado com esses filtros.'", (await page.getByText("Nenhum processo encontrado com esses filtros.").count()) === 1)
  await page.getByPlaceholder("Buscar família, pessoa, cartório…").fill("")
  if (nFases > 1) {
    const outra = botoes.nth(1)
    const rotuloOutra = (await outra.innerText()).replace(/\s*\d+$/, "")
    await outra.click()
    ok("trocar de fase troca a tabela, o título e os cartões (sem limpar os filtros)", (await page.locator(".tor-pg-titulo").innerText()).startsWith(rotuloOutra) && (await outra.getAttribute("aria-pressed")) === "true")
  }
  await botoes.nth(0).click()
  await page.waitForTimeout(600)
  // volta à fase com mais processos para o Relatório
  const maior = await botoes.evaluateAll((els) => { let m = 0, i = 0; els.forEach((e, k) => { const n = Number((e.textContent ?? "").replace(/\D+/g, "")); if (n > m) { m = n; i = k } }); return i })
  await botoes.nth(maior).click()
  await page.waitForTimeout(800)

  secao("RELATÓRIO DE CONTROLE (modal) e EXPORTAÇÃO")
  const familia = (await page.locator(".tor-pf-fam a").first().innerText()).trim()
  await page.locator(".tor-pf-rel").first().click()
  const dlg = page.getByRole("dialog")
  ok("T217/T218 modal 'Relatório de controle · <família>' com o texto do protótipo", (await dlg.innerText()).includes(`Relatório de controle · ${familia}`) && (await dlg.innerText()).includes("Todas as certidões da família, em todas as fases, com passo, responsável, datas e histórico resumido. Mesmo motor da aba Relatórios, já filtrado pela família."))
  ok("botões: Exportar CSV · Exportar Excel · Exportar PDF · Fechar · ✕", (await dlg.getByRole("button").allInnerTexts()).join("|") === "✕|Exportar CSV|Exportar Excel|Exportar PDF|Fechar")
  await page.screenshot({ path: "prototipo-torre/impl/processos-e2e-relatorio.png" })
  await dlg.locator(".tor-rel-btn.pri").click()
  ok("T220 'Fechar' fecha sem aviso", (await page.getByRole("dialog").count()) === 0 && (await page.locator(".tor-toast").count()) === 0)
  for (const [rot, ext] of [["Exportar CSV", ".csv"], ["Exportar Excel", ".xlsx"], ["Exportar PDF", ".pdf"]] as const) {
    await page.locator(".tor-pf-rel").first().click()
    const [download] = await Promise.all([page.waitForEvent("download", { timeout: 120000 }), page.getByRole("dialog").getByRole("button", { name: rot, exact: true }).click()])
    ok(`T219 ${rot}: baixa o arquivo REAL (${download.suggestedFilename()})`, download.suggestedFilename().toLowerCase().endsWith(ext))
    await page.waitForTimeout(500)
    ok("…fecha o modal e mostra 'Relatório exportado com todas as linhas' (sem Desfazer)", (await page.getByRole("dialog").count()) === 0 && (await page.locator(".tor-toast").innerText()).includes("Relatório exportado com todas as linhas") && (await page.locator(".tor-toast button", { hasText: "Desfazer" }).count()) === 0)
  }
  await page.locator(".tor-pf-rel").first().click()
  await page.getByRole("dialog").locator(".tor-rel-x").click()
  ok("T220 '✕' fecha sem novo aviso", (await page.getByRole("dialog").count()) === 0)

  secao("FOCO")
  await page.locator(".tor-pf-foco").first().click()
  await page.waitForURL(/\/torre\/processo\/\d+/, { timeout: 60000 })
  ok("T216 'Foco' abre o Processo", /\/torre\/processo\/\d+$/.test(page.url()))

  ok("nenhum erro de página nem resposta ≥ 400 nas APIs durante o roteiro", erros.length === 0, erros.join(" | "))
  await browser.close()
  console.log(`\n${falhou === 0 ? "✅ PASSOU" : "❌ FALHOU"}: ${passou} ok, ${falhou} falhas`)
  process.exit(falhou ? 1 : 0)
}
main().catch((e) => { console.error(e); process.exit(1) })
